# ==========================================================
  # 由于这个策略是isaaclab训练出来的，但是又要部署到实际机器上，所以，在进行给策略进行输入的时候，关节的顺序必须是isaaclab的顺序
  # 在策略输出关节动作的时候，输出的是isaaclab中的关节顺序，必须要转换到机器人的关节顺序上。
# ==========================================================
control_dt: 0.02

msg_type: "hg"        # "hg" for G1
imu_type: "pelvis"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"
right_arm_topic: "rt/user/g1/right_arm_lowcmd"
# 策略路径 (导出的 TorchScript JIT 模型)
policy_path: "/home/cjh/TienKung-Lab/logs/g1_squat/2026-07-22_20-44-15/exported/policy.pt"

# 使用 10 帧观测历史 (与训练一致)
obs_history_length: 10

# 15维动作控制电机：left leg + right leg + waist
action2motor_idx: [0, 1, 2, 3, 4, 5,
                   6, 7, 8, 9, 10, 11,
                   12, 13, 14]

# action在29维IsaacLab joint order中对应哪些关节
action_joint_ids: [0, 3, 6, 9, 13, 17,
                   1, 4, 7, 10, 14, 18,
                   2, 5, 8]


# G1 关节映射: Isaac Lab 顺序 -> 电机索引
# Isaac Lab 顺序: [left_hip_pitch, right_hip_pitch, waist_yaw, left_hip_roll, right_hip_roll, ...]
joint2motor_idx: [0, 6, 12, 1, 7, 13, 2, 8, 14, 3, 9, 15, 22, 4, 10, 16, 23, 5, 11, 17, 24, 18, 25, 19, 26, 20, 27, 21, 28] # 是isaaclab的关节在真实世界中的索引

# PD 增益 (Isaac Lab 顺序)
kps: [200, 200, 200, 150, 150, 200, 150, 150, 200, 200, 200, 100, 100, 20, 20, 100, 100, 20, 20, 50, 50, 50, 50, 40, 40, 40, 40, 40, 40]
kds: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

# 默认关节位置 (Isaac Lab 顺序)
default_joint_pos: [-0.2, -0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.42, 0.42, 0.35, 0.35, -0.23, -0.23, 0.18, -0.18, 0.0, 0.0, 0.0, 0.0, 0.87, 0.87, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

# 观测缩放
ang_vel_scale: 1.0
dof_pos_scale: 1.0
dof_vel_scale: 1.0
action_scale: 0.25
command_scale: [1.0]

# 观测维度 (带步态相位版本)

num_joints: 29
num_actions: 15
num_obs: 81  # 单帧本体观测的维度
num_policy_obs: 810


# 速度命令范围
command_range: {height:[0.46,0.77]}

height_command:
  stand_height: 0.77
  squat_height: 0.1
  max_delta_per_s: 0.05